// Models configuration: Primary and Fallback
const PRIMARY_MODEL = "gemini-2.5-flash-lite";
const FALLBACK_MODEL = "gemini-2.0-flash-lite";
const GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta/models";

// Helper: Standard JSON response
function jsonResponse(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
    },
  });
}

// Session authentication check
async function authenticateSession(request, env) {
  const authHeader = request.headers.get("Authorization");
  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return null;
  }
  const token = authHeader.replace("Bearer ", "").trim();
  const sessionData = await env.NOVEL_STORE.get(`session:${token}`, { type: "json" });

  if (!sessionData) {
    return null;
  }

  if (Date.now() > sessionData.expiresAt) {
    await env.NOVEL_STORE.delete(`session:${token}`);
    return null;
  }

  return { token, username: sessionData.username };
}

// Call Google Gemini REST endpoint
async function callGemini(model, apiKey, systemInstruction, contents) {
  const url = `${GEMINI_API_BASE}/${model}:generateContent?key=${apiKey}`;

  const payload = {
    contents,
    generationConfig: {
      temperature: 0.7,
      topP: 0.95,
      maxOutputTokens: 2048,
    },
  };

  if (systemInstruction) {
    payload.systemInstruction = {
      parts: [{ text: systemInstruction }],
    };
  }

  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorDetails = await response.text();
    throw new Error(`Model ${model} returned status ${response.status}: ${errorDetails}`);
  }

  const result = await response.json();
  const candidate = result.candidates?.[0];
  const responseText = candidate?.content?.parts?.[0]?.text;

  if (!responseText) {
    throw new Error("No text response generated by model.");
  }

  return responseText;
}

// Handle OPTIONS preflight
export async function onRequestOptions() {
  return new Response(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
    },
  });
}

// Handle POST: Chat with Novel Assistant using BYOK Gemini API key
export async function onRequestPost(context) {
  const { request, env } = context;
  const user = await authenticateSession(request, env);

  if (!user) {
    return jsonResponse({ error: "Unauthorized" }, 401);
  }

  try {
    const body = await request.json();
    const { novelId, messages } = body;

    if (!Array.isArray(messages) || messages.length === 0) {
      return jsonResponse({ error: "A non-empty messages array is required." }, 400);
    }

    // 1. Fetch user's stored Gemini BYOK key
    const userProfile = await env.NOVEL_STORE.get(`user:${user.username}`, { type: "json" });
    const apiKey = userProfile?.geminiApiKey;

    if (!apiKey) {
      return jsonResponse({
        error: "No Gemini API key found. Please save your API key in settings first.",
      }, 400);
    }

    // 2. Fetch novel overview context if novelId is provided
    let storyOverview = "";
    let novelTitle = "";
    if (novelId) {
      const novel = await env.NOVEL_STORE.get(`novel:${novelId}`, { type: "json" });
      if (novel && novel.owner === user.username) {
        novelTitle = novel.title || "";
        storyOverview = novel.overview || "";
      }
    }

    // 3. Verify mandatory 500-word story overview requirement
    const wordCount = storyOverview.trim().split(/\s+/).filter(Boolean).length;
    if (wordCount < 500) {
      return jsonResponse({
        error: `Story overview contains ${wordCount} words. You must provide at least 500 words in the Story Overview before the AI assistant can access your novel context.`,
        wordCount,
        requiresOverview: true,
      }, 403);
    }

    // 4. Construct strict expert system prompt
    const systemPrompt = `You are a master novel writing consultant, developmental editor, and literary craft specialist.
Your sole mission is to assist the author with writing, structuring, narrating, and refining their active novel.
Under NO circumstances are you to engage in unrelated small talk, fluff, generic conversational filler, or topics outside of fiction writing craft and this story.

STORY CONTEXT:
- Novel Title: "${novelTitle}"
- Mandatory Story Overview (500+ words provided by author):
${storyOverview}

GUIDELINES FOR YOUR RESPONSES:
1. Ground all your advice directly in the provided story overview, its themes, pacing, world mechanics, and character conflicts.
2. Deliver sharp, insightful narrative analysis: pacing dynamics, scene construction, character voice, sensory prose, narrative stakes, and dialogue subtext.
3. Be concise, actionable, and laser-focused on writing craft. Cut pleasantries; jump straight into high-caliber storytelling critique and solutions.`;

    // 5. Format conversation history for Gemini API (user / model turns)
    const formattedContents = messages.map(msg => ({
      role: msg.role === "assistant" ? "model" : "user",
      parts: [{ text: msg.content }],
    }));

    // 6. Execute Primary Model with Fallback mechanism
    let replyText = "";
    let modelUsed = PRIMARY_MODEL;

    try {
      replyText = await callGemini(PRIMARY_MODEL, apiKey, systemPrompt, formattedContents);
    } catch (primaryErr) {
      console.warn(`Primary model ${PRIMARY_MODEL} failed, switching to fallback ${FALLBACK_MODEL}:`, primaryErr.message);
      try {
        modelUsed = FALLBACK_MODEL;
        replyText = await callGemini(FALLBACK_MODEL, apiKey, systemPrompt, formattedContents);
      } catch (fallbackErr) {
        return jsonResponse({
          error: "Both primary and fallback AI models failed to fulfill the request.",
          details: fallbackErr.message,
        }, 502);
      }
    }

    return jsonResponse({
      message: replyText,
      modelUsed,
    });
  } catch (err) {
    return jsonResponse({ error: "Server error", details: err.message }, 500);
  }
}
